In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

imd = pd.read_csv(r'D:\IMARTICUS\IMDB Dataset.csv')

In [2]:
imd.shape

(50000, 2)

In [3]:
imd.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
imd.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
imd.sentiment.value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [7]:
imd['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [8]:
imd.review = imd.review.str.lower()

In [9]:
imd.sentiment = imd.sentiment.str.lower()

In [33]:
imd.sentiment = imd.sentiment.replace({'positive' : 1 , 'negative' : 0})

In [34]:
import string
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [35]:
from sklearn.feature_extraction.text import CountVectorizer 

In [36]:
def text_process(mess):            ### creating a function
    """                                                        ## a docstring
    1. remove the punctuation
    2. remove the stopwords
    3. return the list of clean textwords
    
    """
    nopunc = [char for char in mess if char  not in string.punctuation]
    nopunc = "".join(nopunc)
    
    return [ word for word in nopunc.split() if word not in ENGLISH_STOP_WORDS]


In [51]:
bow_transformer = CountVectorizer(analyzer=text_process).fit_transform(imd['review'])

In [52]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(bow_transformer , imd.sentiment)

In [53]:
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()

In [54]:
NB.fit(x_train , y_train)

MultinomialNB()

In [55]:
pred_test = NB.predict(x_test)

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score
conmat_NB = confusion_matrix(y_test , pred_test)

conmat_NB

array([[5488,  689],
       [1006, 5317]], dtype=int64)

In [57]:
accuracy_score(y_test , pred_test)*100

86.44

In [58]:
conmat_NB.diagonal().sum() / conmat_NB.sum() * 100

86.44

## DECISION TREE

In [59]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(max_depth= 4)

In [60]:
DT.fit(x_train , y_train)

DecisionTreeClassifier(max_depth=4)

In [61]:
pred_test_DT = DT.predict(x_test)
pred_test_DT

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [62]:
pred_test_DT.shape

(12500,)

In [63]:
conmat_DT = confusion_matrix(y_test , pred_test_DT)
conmat_DT

array([[2744, 3433],
       [ 651, 5672]], dtype=int64)

In [64]:
accuracy_score(y_test , pred_test_DT)*100

67.328